Linear Algebra 


In [12]:
#NUMPY

import numpy as np
np1 =  np.array([11,12,13,14,15,16,17,18,19,20])
print(np1)
print(np1[5]) #accesing element 

np1.shape #no of elements present in array

np2 = np.arange(0,20,3)
print(np2) #step

np3 = np.full((5), 3)
print(np3) #prints 3 for 5 times in an array

np4 = np.full((2,10), 5)
print(np4) #prints 5 for 10 times in multidimentional array

#slicing in numpy arrays
arr = np.array([2,4,6,8,10,12])
print(arr[1:4]) 
print(arr[-4:-1]) #negtive slicing

arr1 = np.array([[1,2,3,4,5], [6,7,8,9,10]]) #2d array slicing
print(arr1[0,3])
print(arr1[1,2])
print(arr1[0:2, 1:3])

#Universal functions in numpy
print(np.sqrt(arr)) #square root
print(np.exp(arr)) #exponential 
print(np.sin(arr)) #sin values
print(np.cos(arr)) #cosine values

#Sorting Numpy array
nparr = np.array([7,2,8,1,9,12,3])
print(nparr)
print(np.sort(nparr))

nparr1 = np.array(["hawkeye", "steve", "stephen", "bucky","loki","thor"])
print(np.sort(nparr1)) #sorts according to alphabetical order

nparr2 = np.array([[76,22,1,8,47],[10,3,54,45,82]])
print(nparr2)
print(np.sort(nparr2)) #sorting 2-d arrays

n_arr = np.array([18,45,31,99,10,3,1])
x = np.where(n_arr == 45)
print(x[0]) #prints index of element to be searched

y = np.where(n_arr % 2 == 1)
print(y[0]) #prints odd items from array


[11 12 13 14 15 16 17 18 19 20]
16
[ 0  3  6  9 12 15 18]
[3 3 3 3 3]
[[5 5 5 5 5 5 5 5 5 5]
 [5 5 5 5 5 5 5 5 5 5]]
[4 6 8]
[ 6  8 10]
4
8
[[2 3]
 [7 8]]
[1.41421356 2.         2.44948974 2.82842712 3.16227766 3.46410162]
[7.38905610e+00 5.45981500e+01 4.03428793e+02 2.98095799e+03
 2.20264658e+04 1.62754791e+05]
[ 0.90929743 -0.7568025  -0.2794155   0.98935825 -0.54402111 -0.53657292]
[-0.41614684 -0.65364362  0.96017029 -0.14550003 -0.83907153  0.84385396]
[ 7  2  8  1  9 12  3]
[ 1  2  3  7  8  9 12]
['bucky' 'hawkeye' 'loki' 'stephen' 'steve' 'thor']
[[76 22  1  8 47]
 [10  3 54 45 82]]
[[ 1  8 22 47 76]
 [ 3 10 45 54 82]]
[1]
[1 2 3 5 6]


In [15]:
#PANDAS

import pandas as pd
import numpy as np
from numpy.random import randn

my_data = randn(4,3) #rows columns
my_rows = ['A','B','C','D']
my_cols = ['mon','wed','sat']

my_df = pd.DataFrame(my_data, my_rows, my_cols)
my_df

mon       wed       sat
A  0.042011  0.580825  1.859334
B  1.076985 -0.025231  0.045669
C  0.961039 -0.142732  1.647567
D -0.184904 -0.419284 -0.384787

In [5]:
import pandas as pd
df = pd.read_csv('archive\dog_breeds.csv')
df



<>:2: SyntaxWarning: invalid escape sequence '\d'
<>:2: SyntaxWarning: invalid escape sequence '\d'
C:\Users\SOHAM\AppData\Local\Temp\ipykernel_7064\3296345550.py:2: SyntaxWarning: invalid escape sequence '\d'
  df = pd.read_csv('archive\dog_breeds.csv')


Breed Country of Origin                     Fur Color  \
0       Labrador Retriever            Canada      Yellow, Black, Chocolate   
1          German Shepherd           Germany                    Black, Tan   
2                  Bulldog           England                    White, Red   
3                   Poodle            France  White, Black, Brown, Apricot   
4                   Beagle           England        White, Tan, Red, Lemon   
..                     ...               ...                           ...   
112  Catahoula Leopard Dog     United States                  Merle, Black   
113         Cocker Spaniel           England                  Black, Brown   
114    Miniature Shiba Inu             Japan                   Red, Sesame   
115       Belgian Tervuren           Belgium                          Fawn   
116          Pharaoh Hound             Malta                           Red   

    Height (in) Color of Eyes Longevity (yrs)  \
0         21-24         Brown          10-Dec   
1         22-26         Brown          07-Oct   
2        Dec-16           NaN          08-Oct   
3        Oct-15   Brown, Blue          Dec-15   
4         13-15         Brown          Dec-15   
..          ...           ...             ...   
112       20-26         Brown          Dec-14   
113       14-15         Brown          Dec-15   
114       13-16         Brown          Dec-15   
115       22-26         Brown          Dec-14   
116       21-25         Brown          Dec-14   

                                      Character Traits  \
0    Loyal, friendly, intelligent, energetic, good-...   
1    Loyal, intelligent, protective, confident, tra...   
2                           Loyal, calm, gentle, brave   
3    Intelligent, active, affectionate, hypoallergenic   
4           Curious, friendly, energetic, good-natured   
..                                                 ...   
112        Intelligent, energetic, good-natured, loyal   
113      Intelligent, energetic, playful, good-natured   
114      Intelligent, energetic, playful, good-natured   
115        Intelligent, energetic, good-natured, loyal   
116        Intelligent, energetic, good-natured, loyal   

                           Common Health Problems  
0          Hip dysplasia, obesity, ear infections  
1    Hip dysplasia, elbow dysplasia, pancreatitis  
2     Skin allergies, respiratory issues, obesity  
3         Hip dysplasia, epilepsy, bladder stones  
4         Ear infections, hip dysplasia, epilepsy  
..                                            ...  
112   Dental problems, eye issues, skin allergies  
113   Dental problems, eye issues, skin allergies  
114   Dental problems, eye issues, skin allergies  
115   Dental problems, eye issues, skin allergies  
116   Dental problems, eye issues, skin allergies  

[117 rows x 8 columns]

In [ ]:
#pulling data from dataframe

'''df.head() shows first 5 rows '''
'''df.head(7) shows 7 rows '''
'''df.tail(12) shows last 12 rows '''
'''df.shape no of rows and columns present in dataframe'''
'''df['Breed'] shows selected column'''



0         Labrador Retriever
1            German Shepherd
2                    Bulldog
3                     Poodle
4                     Beagle
               ...          
112    Catahoula Leopard Dog
113           Cocker Spaniel
114      Miniature Shiba Inu
115         Belgian Tervuren
116            Pharaoh Hound
Name: Breed, Length: 117, dtype: object

In [ ]:
#count data in df

'''df['Color of Eyes'].value_counts() 
df['Color of Eyes'].value_counts(dropna=False)
df['Fur Color'].value_counts(normalize=True) #counts percentage
df.groupby('Fur Color').size() #unique values '''


Fur Color
Apricot, Fawn                   1
Black, Blue, Fawn, Harlequin    1
Black, Brown                    2
Black, Brown, Grey              1
Black, Brown, Red               1
                               ..
White, Blenheim                 1
White, Cream, Red               1
White, Red                      3
White, Tan, Red, Lemon          1
Yellow, Black, Chocolate        1
Length: 68, dtype: int64

In [ ]:
#fixing incomplete data

df.dropna()  #drops rows with null values
df.dropna(axis=1) #drops columns with null values

Breed Country of Origin Height (in) Longevity (yrs)  \
0       Labrador Retriever            Canada       21-24          10-Dec   
1          German Shepherd           Germany       22-26          07-Oct   
2                  Bulldog           England      Dec-16          08-Oct   
3                   Poodle            France      Oct-15          Dec-15   
4                   Beagle           England       13-15          Dec-15   
..                     ...               ...         ...             ...   
112  Catahoula Leopard Dog     United States       20-26          Dec-14   
113         Cocker Spaniel           England       14-15          Dec-15   
114    Miniature Shiba Inu             Japan       13-16          Dec-15   
115       Belgian Tervuren           Belgium       22-26          Dec-14   
116          Pharaoh Hound             Malta       21-25          Dec-14   

                                      Character Traits  \
0    Loyal, friendly, intelligent, energetic, good-...   
1    Loyal, intelligent, protective, confident, tra...   
2                           Loyal, calm, gentle, brave   
3    Intelligent, active, affectionate, hypoallergenic   
4           Curious, friendly, energetic, good-natured   
..                                                 ...   
112        Intelligent, energetic, good-natured, loyal   
113      Intelligent, energetic, playful, good-natured   
114      Intelligent, energetic, playful, good-natured   
115        Intelligent, energetic, good-natured, loyal   
116        Intelligent, energetic, good-natured, loyal   

                           Common Health Problems  
0          Hip dysplasia, obesity, ear infections  
1    Hip dysplasia, elbow dysplasia, pancreatitis  
2     Skin allergies, respiratory issues, obesity  
3         Hip dysplasia, epilepsy, bladder stones  
4         Ear infections, hip dysplasia, epilepsy  
..                                            ...  
112   Dental problems, eye issues, skin allergies  
113   Dental problems, eye issues, skin allergies  
114   Dental problems, eye issues, skin allergies  
115   Dental problems, eye issues, skin allergies  
116   Dental problems, eye issues, skin allergies  

[117 rows x 6 columns]